name: atelet
description: "Una aplicaci贸n para la gesti贸n y ejecuci贸n de rutinas de entrenamiento."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  go_router: ^17.1.0
  hux: ^1.0.1
  logging: ^1.3.0
  mocktail: ^1.0.4
  intl: ^0.20.2
  icons_launcher: ^3.0.3
  shared_preferences: ^2.5.4
  disco: ^2.0.0
  flutter_solidart: ^2.7.1
  package_info_plus: ^9.0.0
  flutter_form_builder: ^10.3.0+2
  shadcn_flutter: ^0.0.51
  form_builder_validators: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
  lints: ^6.1.0
  arb_merge: ^1.2.2

flutter:
  uses-material-design: true

  generate: true

  fonts:
    - family: Archivo
      fonts:
        - asset: assets/fonts/Archivo-Variable.ttf
        - asset: assets/fonts/Archivo-Italic-Variable.ttf
          style: italic

icons_launcher:
  image_path: "assets/logo/shape.png"
  platforms:
    android:
      enable: true

# Mezclar archivos de traducci贸n en la carpeta lib/l10n
arb_merge:
  sources: assets/l10n
  destination: lib/l10n
  sort: false
  pattern: "app_{lang}.arb"
  verbose: false
